### ISSUE TITLE
LED lights not working

### ISSUE THREAD

**Issue by nateo87** [tebl/8BIT-Wave#1]
For some reason, the LEDs aren't doing anything on my build. Everything else works just fine, tape loads with no problems, and the LEDs I'm using do work when attached to their own power supply. Is there something in the MaxDuino software perhaps that is denying operation?

**Comment by tebl** [comment]
The LEDs aren't used by the Maxduino firmware, I added them to have
somehing to play around with from the Arduino IDE. There should be a 3-pad
jumper that can be used to explicitly tie the PWR LED to VCC (always on).

man. 31. mai 2021, 22:53 skrev nateo87 ***@***.***>:
